server.port=8082
# 配置 SMTP 服务器地址
spring.mail.host=smtp.qq.com
# 使用的邮件协议
spring.mail.protocol=smtp
# 默认的邮件编码
spring.mail.default-encoding=UTF-8
# 配置密码，注意，不是真正的密码，而是刚刚申请到的授权码
spring.mail.password=ypcyatczrbvvbeci
# 配置邮箱用户名
spring.mail.username=542270559@qq.com
# SMTP 服务器的端口
spring.mail.port=587
# 配饰 SSL 加密工厂
spring.mail.properties.mail.stmp.socketFactory.class=javax.net.ssl.SSLSocketFactory
# 表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
spring.mail.properties.mail.debug=true
#--------------- RabbitMQ ------------------------
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.host=127.0.0.1
# 15672 是mq后台管理页面的端口号，这里应该使用 5672
spring.rabbitmq.port=5672
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=100
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.password=
spring.redis.database=0